import type {Metadata} from "next";
import "./reset.css";
import "./font.css"
import * as stylex from "@stylexjs/stylex"
import {colors, darkMode, lightMode} from "../ui/tokens/colors.stylex"
import Header from "@/app/Header";
import Footer from "@/app/Footer";
import DarkModeProvider from "@/app/DarkModeProvider";
import {cookies} from "next/headers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const mode = cookies().get('color-mode')?.value;

    return (
        <DarkModeProvider>
            <html lang="en" {...stylex.props(rootStyles.showcase, rootStyles.theme, mode === 'dark' && darkMode, mode === 'light' && lightMode)}>
            <body>
                <Header/>
                {children}
                <Footer/>
            </body>
            </html>
        </DarkModeProvider>
    );
}

const rootStyles = stylex.create({
    theme: {
        background: colors.background,
        color: colors.text
    },
    showcase: {
        minHeight: '100dvh',
        minWidth: '100dvw'
    }
})
